import { StyleSheet } from 'react-native';
import { Spacing, BorderRadius, Theme } from '@/constants/theme';

export const createStyles = (theme: Theme) => {
  return StyleSheet.create({
    scrollContent: {
      flexGrow: 1,
      paddingBottom: 100,
    },
    header: {
      paddingHorizontal: Spacing.xl,
      paddingTop: Spacing["2xl"],
      paddingBottom: Spacing.lg,
    },
    title: {
      fontSize: 28,
      fontWeight: '800',
      color: theme.textPrimary,
    },
    profileCard: {
      marginHorizontal: Spacing.xl,
      marginTop: Spacing.lg,
      borderRadius: BorderRadius["2xl"],
      padding: 24,
      backgroundColor: theme.backgroundDefault,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.7)',
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 20,
      elevation: 6,
      alignItems: 'center',
    },
    avatar: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: theme.backgroundTertiary,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: Spacing.md,
      borderWidth: 3,
      borderColor: 'rgba(255,255,255,0.7)',
    },
    userName: {
      fontSize: 20,
      fontWeight: '800',
      color: theme.textPrimary,
    },
    userLevel: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.textSecondary,
      marginTop: 4,
    },
    statsGrid: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      marginTop: Spacing["2xl"],
      paddingHorizontal: Spacing.xl,
    },
    statCard: {
      flex: 1,
      marginHorizontal: Spacing.sm,
      borderRadius: BorderRadius.xl,
      padding: 20,
      backgroundColor: theme.backgroundDefault,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.7)',
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.12,
      shadowRadius: 12,
      elevation: 4,
      alignItems: 'center',
    },
    statIcon: {
      width: 44,
      height: 44,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: Spacing.sm,
    },
    statValue: {
      fontSize: 22,
      fontWeight: '800',
      color: theme.textPrimary,
    },
    statLabel: {
      fontSize: 11,
      fontWeight: '600',
      color: theme.textSecondary,
      marginTop: 2,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: Spacing.xl,
      marginTop: Spacing["2xl"],
      marginBottom: Spacing.lg,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: '800',
      color: theme.textPrimary,
    },
    recentList: {
      paddingHorizontal: Spacing.xl,
    },
    recentItem: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 16,
      borderRadius: BorderRadius.xl,
      backgroundColor: theme.backgroundDefault,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.7)',
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 3,
      marginBottom: Spacing.md,
    },
    recentBookCover: {
      width: 50,
      height: 70,
      borderRadius: 8,
      backgroundColor: theme.backgroundTertiary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    recentBookInfo: {
      flex: 1,
      marginLeft: Spacing.lg,
    },
    recentBookTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: theme.textPrimary,
    },
    recentBookProgress: {
      fontSize: 12,
      fontWeight: '500',
      color: theme.textSecondary,
      marginTop: 4,
    },
    menuSection: {
      paddingHorizontal: Spacing.xl,
      marginTop: Spacing["2xl"],
    },
    menuItem: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 16,
      borderRadius: BorderRadius.xl,
      backgroundColor: theme.backgroundDefault,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.7)',
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 3,
      marginBottom: Spacing.md,
    },
    menuIcon: {
      width: 44,
      height: 44,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: Spacing.lg,
    },
    menuText: {
      flex: 1,
      fontSize: 15,
      fontWeight: '600',
      color: theme.textPrimary,
    },
    menuArrow: {
      marginLeft: Spacing.md,
    },
    loadingContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 60,
    },
    emptyContainer: {
      alignItems: 'center',
      paddingVertical: 40,
    },
    emptyText: {
      fontSize: 14,
      fontWeight: '500',
      color: theme.textSecondary,
    },
  });
};
