import { StyleSheet } from 'react-native';
import { Spacing, BorderRadius, Theme } from '@/constants/theme';

export const createStyles = (theme: Theme) => {
  return StyleSheet.create({
    container: {
      flex: 1,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: Spacing.xl,
      paddingTop: Spacing["2xl"],
      paddingBottom: Spacing.lg,
      backgroundColor: theme.backgroundDefault,
    },
    backButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.backgroundTertiary,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.7)',
    },
    title: {
      flex: 1,
      textAlign: 'center',
      marginRight: 44,
    },
    content: {
      flex: 1,
    },
    bookSelector: {
      marginHorizontal: Spacing.xl,
      marginTop: Spacing.lg,
      marginBottom: Spacing.lg,
    },
    bookSelectorLabel: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textSecondary,
      marginBottom: Spacing.sm,
    },
    bookSelectorButton: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 16,
      borderRadius: BorderRadius.xl,
      backgroundColor: theme.backgroundDefault,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.7)',
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 3,
    },
    bookSelectorText: {
      flex: 1,
      fontSize: 15,
      fontWeight: '600',
      color: theme.textPrimary,
    },
    bookSelectorPlaceholder: {
      flex: 1,
      fontSize: 15,
      fontWeight: '500',
      color: theme.textMuted,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: Spacing.xl,
      marginBottom: Spacing.md,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: theme.textPrimary,
    },
    currentResources: {
      marginHorizontal: Spacing.xl,
      marginBottom: Spacing.lg,
    },
    resourceItem: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 16,
      borderRadius: BorderRadius.xl,
      backgroundColor: theme.backgroundDefault,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.7)',
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 3,
      marginBottom: Spacing.sm,
    },
    resourceIcon: {
      width: 40,
      height: 40,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: Spacing.lg,
    },
    resourceInfo: {
      flex: 1,
    },
    resourceType: {
      fontSize: 11,
      fontWeight: '600',
      color: theme.textMuted,
      marginBottom: 2,
    },
    resourceName: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textPrimary,
    },
    removeButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#FFEEF0',
    },
    fileList: {
      paddingHorizontal: Spacing.xl,
    },
    fileItem: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 16,
      borderRadius: BorderRadius.xl,
      backgroundColor: theme.backgroundDefault,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.7)',
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 3,
      marginBottom: Spacing.sm,
    },
    fileItemLinked: {
      borderColor: theme.success,
      backgroundColor: '#F0FDF4',
    },
    fileIcon: {
      width: 44,
      height: 44,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: Spacing.lg,
    },
    fileInfo: {
      flex: 1,
    },
    fileName: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textPrimary,
      marginBottom: 2,
    },
    fileSize: {
      fontSize: 12,
      fontWeight: '500',
      color: theme.textMuted,
    },
    linkButton: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.primary,
    },
    linkButtonText: {
      fontSize: 12,
      fontWeight: '700',
      color: '#FFFFFF',
    },
    linkedBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: BorderRadius.lg,
      backgroundColor: '#E0F8EC',
    },
    linkedText: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.success,
      marginLeft: 4,
    },
    pathBar: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: Spacing.xl,
      paddingVertical: Spacing.md,
      backgroundColor: theme.backgroundTertiary,
    },
    pathText: {
      fontSize: 13,
      fontWeight: '500',
      color: theme.textSecondary,
    },
    emptyContainer: {
      alignItems: 'center',
      paddingVertical: 60,
    },
    emptyIcon: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: theme.backgroundTertiary,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: Spacing.lg,
    },
    emptyText: {
      fontSize: 14,
      fontWeight: '500',
      color: theme.textSecondary,
    },
    loadingContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    // Book Picker Modal
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'flex-end',
    },
    modalContent: {
      backgroundColor: theme.backgroundDefault,
      borderTopLeftRadius: BorderRadius["2xl"],
      borderTopRightRadius: BorderRadius["2xl"],
      maxHeight: '70%',
      paddingBottom: Spacing["3xl"],
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: Spacing.xl,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: '800',
      color: theme.textPrimary,
    },
    bookOption: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: theme.borderLight,
    },
    bookOptionSelected: {
      backgroundColor: theme.backgroundTertiary,
    },
    bookCover: {
      width: 40,
      height: 56,
      borderRadius: 6,
      backgroundColor: theme.border,
      marginRight: Spacing.lg,
    },
    bookOptionTitle: {
      fontSize: 15,
      fontWeight: '600',
      color: theme.textPrimary,
    },
    bookOptionLevel: {
      fontSize: 12,
      fontWeight: '500',
      color: theme.textSecondary,
      marginTop: 2,
    },
  });
};
