import { StyleSheet } from 'react-native';
import { Spacing, BorderRadius, Theme } from '@/constants/theme';

export const createStyles = (theme: Theme) => {
  return StyleSheet.create({
    container: {
      flex: 1,
    },
    loadingContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: Spacing.xl,
      paddingTop: Spacing["2xl"],
      paddingBottom: Spacing.lg,
      backgroundColor: theme.backgroundDefault,
    },
    backButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.backgroundTertiary,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.7)',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      marginRight: 40,
    },
    content: {
      flex: 1,
    },
    pdfContainer: {
      flex: 1,
      backgroundColor: theme.backgroundTertiary,
    },
    playerCard: {
      margin: Spacing.xl,
      borderRadius: BorderRadius["2xl"],
      padding: 20,
      backgroundColor: theme.backgroundDefault,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.7)',
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 20,
      elevation: 6,
    },
    playerHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: Spacing.lg,
    },
    playerIcon: {
      width: 48,
      height: 48,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: Spacing.lg,
      backgroundColor: '#EDE8FF',
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.7)',
    },
    playerTitle: {
      flex: 1,
    },
    playerSubtitle: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.textSecondary,
      marginTop: 2,
    },
    playButton: {
      width: 56,
      height: 56,
      borderRadius: 28,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.primary,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.3)',
      shadowColor: '#5A3ED9',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 6,
    },
    progressContainer: {
      marginTop: Spacing.lg,
    },
    progressBar: {
      height: 6,
      borderRadius: 3,
      backgroundColor: theme.border,
    },
    progressFill: {
      height: '100%',
      borderRadius: 3,
      backgroundColor: theme.primary,
    },
    timeRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: Spacing.sm,
    },
    timeText: {
      fontSize: 11,
      fontWeight: '600',
      color: theme.textMuted,
    },
    controlsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: Spacing.lg,
      gap: 32,
    },
    controlButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.backgroundTertiary,
    },
    bottomBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-around',
      paddingVertical: Spacing.lg,
      paddingHorizontal: Spacing.xl,
      backgroundColor: theme.backgroundDefault,
      borderTopWidth: 1,
      borderTopColor: theme.border,
    },
    bottomButton: {
      alignItems: 'center',
    },
    bottomIcon: {
      width: 48,
      height: 48,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.backgroundTertiary,
      marginBottom: Spacing.xs,
    },
    bottomText: {
      fontSize: 11,
      fontWeight: '600',
      color: theme.textSecondary,
    },
    resourcesCard: {
      margin: Spacing.xl,
      borderRadius: BorderRadius["2xl"],
      padding: 20,
      backgroundColor: theme.backgroundDefault,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.7)',
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 20,
      elevation: 6,
    },
    resourceItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: Spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    resourceIcon: {
      width: 40,
      height: 40,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: Spacing.lg,
    },
    resourceInfo: {
      flex: 1,
    },
    resourceTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textPrimary,
    },
    resourceSize: {
      fontSize: 11,
      fontWeight: '500',
      color: theme.textMuted,
      marginTop: 2,
    },
    emptyContainer: {
      alignItems: 'center',
      paddingVertical: 60,
    },
    emptyText: {
      fontSize: 14,
      fontWeight: '500',
      color: theme.textSecondary,
      marginTop: Spacing.md,
    },
  });
};
